<?php
/**
 * Checks whether a file under uploads belongs to someone other than a variant row.
 *
 * @package TrustOptimize
 */

namespace TrustOptimize\Files;

use TrustOptimize\Storage\VariantRepository;

/**
 * Class FileOwnership
 *
 * Two exact lookups, no scans: a variant file may be shared with the variant of another
 * attachment (duplicated media), and may be the original of another attachment
 * (files registered by importers). Sizes generated by WordPress are not checked: their
 * names (`photo-300x200.jpg`) cannot equal a variant name (`photo.jpg.webp`).
 */
class FileOwnership {

	/**
	 * Variant repository.
	 *
	 * @var VariantRepository
	 */
	private $variants;

	/**
	 * Constructor.
	 *
	 * @param VariantRepository $variants Variant repository.
	 */
	public function __construct( VariantRepository $variants ) {
		$this->variants = $variants;
	}

	/**
	 * Whether a variant row of another attachment points at the same file.
	 *
	 * @param int    $attachment_id Attachment whose row is being handled.
	 * @param string $relative_path Path relative to uploads.
	 * @return bool
	 */
	public function shared_with_other_variant( $attachment_id, $relative_path ) {
		if ( '' === $relative_path ) {
			return false;
		}

		return isset( $this->variants->find_other_owners( (int) $attachment_id, array( $relative_path ) )[ $relative_path ] );
	}

	/**
	 * Whether the file is the original of an attachment, other than the given one.
	 *
	 * @param string $relative_path       Path relative to uploads.
	 * @param int    $except_attachment_id Attachment to ignore, 0 to consider all.
	 * @return bool
	 */
	public function is_attachment_file( $relative_path, $except_attachment_id = 0 ) {
		global $wpdb;

		if ( '' === $relative_path ) {
			return false;
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery -- Exact lookup of a core meta key; the answer must be current.
		return (bool) $wpdb->get_var(
			$wpdb->prepare(
				"SELECT 1 FROM {$wpdb->postmeta} WHERE meta_key = '_wp_attached_file' AND meta_value = %s AND post_id <> %d LIMIT 1",
				$relative_path,
				(int) $except_attachment_id
			)
		);
	}
}
