<?php
/**
 * Image processor class
 *
 * @package TrustOptimize
 */

namespace TrustOptimize\Features\Optimization;

use DOMElement;
use TrustOptimize\Admin\Settings;
use TrustOptimize\Frontend\PictureRenderer;
use TrustOptimize\Utils\Helper;
use TrustOptimize\Utils\HtmlFragment;

/**
 * Class ImageProcessor
 */
class ImageProcessor {

	/**
	 * Picture renderer.
	 *
	 * @var PictureRenderer
	 */
	protected $renderer;

	/**
	 * Settings instance.
	 *
	 * @var Settings
	 */
	protected $settings;

	/**
	 * Constructor.
	 *
	 * @param PictureRenderer $renderer Picture renderer.
	 * @param Settings        $settings Settings instance.
	 */
	public function __construct( PictureRenderer $renderer, Settings $settings ) {
		$this->renderer = $renderer;
		$this->settings = $settings;
	}

	/**
	 * Register the frontend filters.
	 */
	public function register() {
		add_filter( 'the_content', array( $this, 'process_content' ), 999 );
		add_filter( 'post_thumbnail_html', array( $this, 'process_thumbnail' ), 999 );
		add_filter( 'wp_get_attachment_image', array( $this, 'process_attachment_image_html' ), 999, 5 );
	}

	/**
	 * Process content to optimize images.
	 *
	 * @param string $content The content to process.
	 *
	 * @return string
	 */
	public function process_content( $content ) {
		return $this->process_content_images( $content );
	}

	/**
	 * Process images in content.
	 *
	 * @param string $content The content to process.
	 *
	 * @return string
	 */
	public function process_content_images( $content ) {
		// Skip if not in frontend or if the feature is disabled or content is empty
		if ( is_admin() || ! $this->is_feature_enabled() || empty( $content ) ) {
			return $content;
		}

		if ( ! extension_loaded( 'dom' ) ) {
			return $content;
		}

		if ( ! HtmlFragment::contains_unprocessed_img( $content ) ) {
			return $content;
		}

		$loaded = HtmlFragment::load( $content );
		if ( null === $loaded ) {
			return $content;
		}

		list( $dom, $root ) = $loaded;

		$images = iterator_to_array( $root->getElementsByTagName( 'img' ) );
		foreach ( $images as $image ) {
			$this->process_image_element( $image );
		}

		return HtmlFragment::save( $dom, $root );
	}

	/**
	 * Process a single image element.
	 *
	 * @param DOMElement $image The image element.
	 */
	private function process_image_element( $image ) {
		$src = $image->getAttribute( 'src' );

		// Already inside a <picture> (libxml may nest it under <source>), or not a real image URL.
		if ( empty( $src ) || 0 === strpos( $src, 'data:' ) || $this->is_inside_picture( $image ) ) {
			return;
		}

		$attachment_id = Helper::get_attachment_id_from_url( $src );

		if ( ! $attachment_id ) {
			return;
		}

		// phpcs:ignore WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
		$tag      = $image->ownerDocument->saveHTML( $image );
		$rendered = $this->renderer->render( $tag, (int) $attachment_id );

		if ( $rendered === $tag ) {
			return;
		}

		$loaded = HtmlFragment::load( $rendered );
		if ( null === $loaded ) {
			return;
		}

		// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
		$picture = $image->ownerDocument->importNode( $loaded[1]->firstChild, true );
		$image->parentNode->replaceChild( $picture, $image );
		// phpcs:enable
	}

	/**
	 * Whether an element has a <picture> ancestor.
	 *
	 * @param DOMElement $element Element.
	 * @return bool
	 */
	private function is_inside_picture( $element ) {
		// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
		for ( $node = $element->parentNode; $node instanceof DOMElement; $node = $node->parentNode ) {
			if ( 'picture' === $node->tagName ) {
				return true;
			}
		}
		// phpcs:enable

		return false;
	}

	/**
	 * Process a post thumbnail.
	 *
	 * @param string $html The thumbnail HTML.
	 *
	 * @return string
	 */
	public function process_thumbnail( $html ) {
		return $this->process_content_images( $html );
	}

	/**
	 * Process HTML generated by wp_get_attachment_image().
	 *
	 * @param string       $html          Attachment image HTML markup.
	 * @param int          $attachment_id Image attachment ID.
	 * @param string|int[] $size          Requested image size.
	 * @param bool         $icon          Whether the image should be treated as an icon.
	 * @param string|array $attr          Attributes for the image markup.
	 * @return string
	 */
	public function process_attachment_image_html( $html, $attachment_id, $size, $icon, $attr ) {
		if ( empty( $html ) || $icon ) {
			return $html;
		}

		return $this->process_content_images( $html );
	}

	/**
	 * Check if the adaptive image feature is enabled.
	 *
	 * @return bool
	 */
	private function is_feature_enabled() {
		return (bool) $this->settings->get( 'enable_adaptive_images', 1 );
	}
}
