<?php
/**
 * The main plugin class
 *
 * @package TrustOptimize
 */

namespace TrustOptimize\Core;

use TrustOptimize\Admin\Admin;
use TrustOptimize\Frontend\Frontend;
use TrustOptimize\Features\Optimization\ImageProcessor;
use TrustOptimize\Features\Optimization\ImageConverter;
use TrustOptimize\Admin\Settings;
use TrustOptimize\Database\DatabaseManager;
use TrustOptimize\Database\ImageModel;

/**
 * Class Plugin
 */
class Plugin {

	/**
	 * The single instance of the class.
	 *
	 * @var Plugin|null
	 */
	protected static $instance = null;

	/**
	 * The loader that's responsible for maintaining and registering all hooks.
	 *
	 * @var Loader
	 */
	protected $loader;

	/**
	 * Admin class instance.
	 *
	 * @var Admin
	 */
	public $admin;

	/**
	 * Frontend class instance.
	 *
	 * @var Frontend
	 */
	public $frontend;

	/**
	 * Image processor instance.
	 *
	 * @var ImageProcessor
	 */
	public $image_processor;

	/**
	 * Image converter instance.
	 *
	 * @var ImageConverter
	 */
	public $image_converter;

	/**
	 * Settings class instance.
	 *
	 * @var Settings
	 */
	public $settings;

	/**
	 * Database manager instance.
	 *
	 * @var DatabaseManager
	 */
	public $db_manager;

	/**
	 * Plugin constructor.
	 */
	public function __construct() {
		$this->loader = new Loader();
	}

	/**
	 * Get the single instance of the plugin.
	 *
	 * @return Plugin
	 */
	public static function get_instance() {
		if ( is_null( self::$instance ) ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Initialize the plugin.
	 */
	public function init() {
		// Load dependencies
		$this->load_dependencies();

		// Register hooks
		$this->register_hooks();

		// Run the loader to register all hooks with WordPress
		$this->loader->run();
	}

	/**
	 * Load the required dependencies.
	 */
	private function load_dependencies() {
		// Initialize database manager
		$this->db_manager = new DatabaseManager();
		$this->db_manager->init();

		// Initialize admin class
		$this->admin = new Admin();

		// Initialize frontend class
		$this->frontend = new Frontend();

		// Initialize image processor
		$this->image_processor = new ImageProcessor();

		// Initialize image converter
		$this->image_converter = new ImageConverter();

		// Initialize settings
		$this->settings = new Settings();
	}

	/**
	 * Register all hooks.
	 */
	private function register_hooks() {
		// Filter to replace image src with optimized version (frontend processing)
		$this->loader->add_filter( 'the_content', $this->image_processor, 'process_content', 999 );

		// Filter for post thumbnails (frontend processing)
		$this->loader->add_filter( 'post_thumbnail_html', $this->image_processor, 'process_thumbnail', 999 );

		// Hook for generating WebP on image upload (backend conversion)
		$this->loader->add_filter( 'wp_generate_attachment_metadata', $this->image_converter, 'handle_image_upload', 10, 2 );

		// Hook for add WebP support
		$this->loader->add_filter( 'upload_mimes', $this, 'allow_modern_image_uploads' );

		// Hook for cleaning up image data when an attachment is deleted
		$this->loader->add_action( 'delete_attachment', $this, 'clean_image_data', 10 );
	}

	/**
	 * Allow modern image formats for uploads.
	 *
	 * @param array $mime_types The list of MIME types.
	 * @return array
	 */
	public function allow_modern_image_uploads( $mime_types ) {
		$mime_types['webp'] = 'image/webp';
		$mime_types['avif'] = 'image/avif';
		return $mime_types;
	}

	/**
	 * Clean up image data when an attachment is deleted
	 *
	 * @param int $attachment_id The attachment ID being deleted.
	 */
	public function clean_image_data( $attachment_id ) {
		// Get all format variations from our custom table before we delete the record
		$image_model = new ImageModel();
		$image_data  = $image_model->get_by_attachment_id( $attachment_id );

		// Delete the physical converted files if we have data
		if ( $image_data && isset( $image_data['metadata']['sizes'] ) ) {
			$this->delete_converted_files( $attachment_id, $image_data['metadata']['sizes'] );
		}

		// Delete the database record
		$image_model->delete( $attachment_id );
	}

	/**
	 * Delete all converted files generated by our plugin
	 *
	 * @param int   $attachment_id The attachment ID
	 * @param array $sizes Image sizes with format data
	 */
	private function delete_converted_files( $attachment_id, $sizes ) {
		// Get the original file path to determine directory
		$original_file_path = get_attached_file( $attachment_id );
		if ( ! $original_file_path || ! file_exists( $original_file_path ) ) {
			return; // Can't proceed without valid file path
		}

		$upload_dir = dirname( $original_file_path );

		// Process each size and its format variations
		foreach ( $sizes as $size_data ) {
			if ( ! isset( $size_data['formats'] ) || ! is_array( $size_data['formats'] ) ) {
				continue;
			}

			// Loop through all format variations (except the original one)
			foreach ( $size_data['formats'] as $format => $format_data ) {
				// Skip if we don't have a filename
				if ( ! isset( $format_data['file'] ) ) {
					continue;
				}

				// Check if this is an original WordPress-generated file by comparing with the original format of the uploaded file
				$original_format = pathinfo( $original_file_path, PATHINFO_EXTENSION );

				// Only delete files in formats different from the original to avoid deleting WordPress-managed files
				if ( $format !== $original_format ) {
					$file_to_delete = trailingslashit( $upload_dir ) . $format_data['file'];

					if ( file_exists( $file_to_delete ) ) {
						wp_delete_file( $file_to_delete );
					}
				}
			}
		}
	}
}
